name: Cache pre-commit hooks

inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-
