name: Enforce conventional commit-style commit messages

on:
  push:

jobs:
  check-commits:
    name: Check commit messages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: '**/requirements-dev.txt'
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
      - name: Cache pre-commit hooks
        uses: ./.github/actions/cache-pre-commit
      - name: Run pre-commit's commit-msg stage on all commits in this push
        run: |
          any_failure=0
          tmp_file="$(mktemp --tmpdir=.)"
          for x in $(git log --format="%H" "${{ github.event.before }}..${{ github.event.after }}")
          do
              echo "Checking commit message for $x"
              git log --format="%B" -n 1 "$x" > "$tmp_file"
              pre-commit run --hook-stage=commit-msg --commit-msg-filename="$tmp_file" || any_failure=1
          done
          rm "$tmp_file"
          exit $any_failure
